kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: faruk/kube-worker-spark-2.2.0-h2.6
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - 'unset SPARK_MASTER_PORT && /opt/spark/sbin/start-slave.sh spark://spark-master:7077'
          resources:
            requests:
              cpu: 100m
