kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: faruk/kube-master-spark-2.2.0-h2.6
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - "/bin/bash"
            - "-c"
            - "--"
          args :
            - 'unset SPARK_MASTER_PORT && echo $(hostname -i) "spark-master" >> /etc/hosts && /opt/spark/sbin/start-master.sh --ip spark-master --port 7077 && sleep infinity'
          resources:
            requests:
              cpu: 100m
